services:
  - type: web
    name: cys-pro-conseil
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: SESSION_SECRET
        generateValue: true
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
